### ISSUE TITLE
Mac 安装 CLI 后运行报错 No module named ssl_match_hostname

### ISSUE THREAD

**Issue by legendtang** [tencentyun/scfcli#12]
安装方式 pip install scf

```
➜ scf help
Traceback (most recent call last):
  File "/usr/local/bin/scf", line 5, in <module>
    from tcfcli.cmds.cli.cli import cli
  File "/usr/local/lib/python2.7/site-packages/tcfcli/cmds/cli/cli.py", line 21, in <module>
    from tcfcli.cmds.local.cli import local
  File "/usr/local/lib/python2.7/site-packages/tcfcli/cmds/local/cli.py", line 4, in <module>
    from .invoke.cli import invoke
  File "/usr/local/lib/python2.7/site-packages/tcfcli/cmds/local/invoke/cli.py", line 5, in <module>
    from tcfcli.cmds.local.common.invoke_context import InvokeContext
  File "/usr/local/lib/python2.7/site-packages/tcfcli/cmds/local/common/invoke_context.py", line 5, in <module>
    import docker
  File "/usr/local/lib/python2.7/site-packages/docker/__init__.py", line 2, in <module>
    from .api import APIClient
  File "/usr/local/lib/python2.7/site-packages/docker/api/__init__.py", line 2, in <module>
    from .client import APIClient
  File "/usr/local/lib/python2.7/site-packages/docker/api/client.py", line 10, in <module>
    from .build import BuildApiMixin
  File "/usr/local/lib/python2.7/site-packages/docker/api/build.py", line 6, in <module>
    from .. import auth
  File "/usr/local/lib/python2.7/site-packages/docker/auth.py", line 9, in <module>
    from .utils import config
  File "/usr/local/lib/python2.7/site-packages/docker/utils/__init__.py", line 3, in <module>
    from .decorators import check_resource, minimum_version, update_headers
  File "/usr/local/lib/python2.7/site-packages/docker/utils/decorators.py", line 4, in <module>
    from . import utils
  File "/usr/local/lib/python2.7/site-packages/docker/utils/utils.py", line 13, in <module>
    from .. import tls
  File "/usr/local/lib/python2.7/site-packages/docker/tls.py", line 5, in <module>
    from .transport import SSLHTTPAdapter
  File "/usr/local/lib/python2.7/site-packages/docker/transport/__init__.py", line 3, in <module>
    from .ssladapter import SSLHTTPAdapter
  File "/usr/local/lib/python2.7/site-packages/docker/transport/ssladapter.py", line 23, in <module>
    from backports.ssl_match_hostname import match_hostname
ImportError: No module named ssl_match_hostname
```

**Comment by anycodes** [comment]
尝试安装一下ssl_match_hostname再试试。

**Comment by legendtang** [comment]
> 尝试安装一下ssl_match_hostname再试试。

这个 module Python 3 才有，内置的，没有这个包
